config/routes.rb
Rails.application.routes.draw do

  resources :accounts do
    resources :payment_profiles
  end

  root 'welcome#index'


  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/account.rb
class Account < ActiveRecord::Base
    has_many :payment_profiles, dependent: :destroy
    validates :email, presence: true, length: { minimum: 5 }
end

app/models/charge.rb
class Charge < ActiveRecord::Base
  belongs_to :payment_profile
  has_many :packages
end

app/models/package.rb
class Package < ActiveRecord::Base
  belongs_to :charge
end

app/models/payment_profile.rb
class PaymentProfile < ActiveRecord::Base
  belongs_to :account
  has_many :charges

  # default = PaymentProfile.where(account_id: params[:id]).update_all(is_default: false)

  def set_default_card?

  end

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def new
    @account = Account.new
  end

  def index
    @account = Account.all
    @charge  = Charge.all
  end

  def create
    @account = Account.new(account_params)

    if @account.save
        redirect_to @account
    else
      render 'new'
    end
  end

  def show
    @account  = Account.find(params[:id])
    @profiles = PaymentProfile.where account_id: params[:id]
    @charge   = Charge.where payment_profile_id: params[:id]
  end

  def edit
    @account = Account.find(params[:id])
  end

  def update
    @account = Account.find(params[:id])

  if @account.update(account_params)
    redirect_to @account
  else
    render 'edit'
  end
end

  private
    def account_params
      params.require(:account).permit(:email)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/payment_profiles_controller.rb
class PaymentProfilesController < ApplicationController
  def list

  end

  def edit
    @account = Account.find(params[:account_id])
    @payment_profiles = @account.payment_profiles.find(params[:id])
  end

  def update
    @account = Account.find(params[:account_id])
    @payment_profiles = @account.payment_profiles.find(params[:id])

    if @payment_profiles.update(payment_profile_params)
      redirect_to @payment_profiles
    else
      render 'edit'
    end
  end

  def create
    @account = Account.find(params[:account_id])
    @payment_profile = @account.payment_profiles.create(payment_profile_params)
    redirect_to account_path(@account)
  end

   def destroy
    @account = Account.find(params[:account_id])
    @payment_profiles = @account.payment_profiles.find(params[:id])
    @payment_profiles.destroy
    redirect_to account_path(@account)
  end


  private
    def payment_profile_params
      params.require(:payment_profile).permit(:last_four, :card_type, :exp_month, :exp_year, :is_default)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/payment_profiles_helper.rb
module PaymentProfilesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/accounts/_edit_card.html.erb
<%= form_for @account do |f| %>
  <% if @profiles.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@profiles.errors.count, "error") %> prohibited
      this profiles from being saved:</h2>
    <ul>
    <% @profiles.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :exp_month %><br>
    <%= f.text_field :exp_month %>
  </p>
  <p>
    <%= f.label :exp_year %><br>
    <%= f.text_field :exp_year %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/accounts/_form.html.erb
<%= form_for @account do |f| %>
  <% if @account.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@account.errors.count, "error") %> prohibited
      this account from being saved:</h2>
    <ul>
    <% @account.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/accounts/edit.html.erb
<h1>Edit Account</h1>

<%= render 'form' %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<h1>Listing account</h1>
<%= link_to 'New account', new_account_path %>
<table>
  <tr>
    <th>Email</th>
    <th colspan="2"></th>
  </tr>

<% @account.each do |account| %>
  <tr>
    <td><%= account.email %></td>
    <td><%= link_to 'Show', account_path(account) %></td>
    <td><%= link_to 'Edit', edit_account_path(account) %></td>
  </tr>
<% end %>
</table>

app/views/accounts/new.html.erb
<h1>New Account</h1>

<%= render 'form' %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<p>
  <strong>Email:</strong>
  <%= @account.email %>
</p>

<p>
  <strong>Stored Card Type:</strong>

  <%= render partial: "payment_profiles/list" %>
</p>


<p>
  <strong>Charge History:</strong>
  <% @charge.each do |charge| %>

  <ul>
    <li>
      <%= charge.package_id %>
      <%= charge.currency_type %>
      <%= charge.amount %>
    </li>
  </ul>
  <% end %>
</p>

<h2>Add a card:</h2>
<%= form_for([@account, @account.payment_profiles.build]) do |f| %>
  <p>
    <%= f.label :last_four %><br>
    <%= f.text_field :last_four %>
  </p>
  <p>
    <%= f.label :card_type %><br>
    <%= f.text_field :card_type %>
  </p>
  <p>
    <%= f.label :exp_month %><br>
    <%= f.text_field :exp_month %>
  </p>
  <p>
    <%= f.label :exp_year %><br>
    <%= f.text_field :exp_year %>
  </p>
  <p>
    <%= f.label :default %><br>
    <%= f.check_box :is_default %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>



<%= link_to 'Back', accounts_path %>
| <%= link_to 'Edit', edit_account_path(@account) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PurchaseFlow</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/payment_profiles/_list.html.erb
<% @profiles.each do |profile| %>
  <ul>
    <li>
      <%= profile.card_type %>, <%= profile.last_four %><%=" [default]" if profile.is_default == 1 %> <%= link_to 'Edit'  %>
      | <%= link_to 'Delete', [profile.account, profile],
           method: :delete,
           data: { confirm: 'Are you sure?' } %>
    </li>
  </ul>
<% end %>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to 'test', controller: 'accounts' %>